# Generated by Django 4.1.13 on 2026-02-08 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_purchase_unit_product_barcode_product_current_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='taxes',
            field=models.ManyToManyField(blank=True, related_name='products', to='core.tax'),
        ),
    ]
